<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<label for="code_snippet"></label><textarea id="code_snippet"></textarea>
<br/>
Time restriction:  <label for="time_restriction"></label><input id="time_restriction" type="text"/>
<br/>
Views restriction:  <label for="views_restriction"></label><input id="views_restriction" type="text"/>
<br/>
<button id="send_snippet" type="submit">Submit</button>
<script type="text/javascript" src="/js/code.js"></script>
</body>
</html>